In [1]:
import pandas as pd
import numpy as np
import matplotlib

In [2]:
cropdata = pd.read_csv(r"../dataset/crop_production.csv")
cropdata.head()

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
0,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Arecanut,1254.0,2000.0
1,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Other Kharif pulses,2.0,1.0
2,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Rice,102.0,321.0
3,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Banana,176.0,641.0
4,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Cashewnut,720.0,165.0

In [3]:
raindata = pd.read_csv(r"../dataset/rainfall in india 1901-2015.csv")
raindata.head()

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
0,ANDAMAN & NICOBAR ISLANDS,1901,49.2,87.1,29.2,2.3,528.8,517.5,365.1,481.1,332.6,388.5,558.2,33.6,3373.2,136.3,560.3,1696.3,980.3
1,ANDAMAN & NICOBAR ISLANDS,1902,0.0,159.8,12.2,0.0,446.1,537.1,228.9,753.7,666.2,197.2,359.0,160.5,3520.7,159.8,458.3,2185.9,716.7
2,ANDAMAN & NICOBAR ISLANDS,1903,12.7,144.0,0.0,1.0,235.1,479.9,728.4,326.7,339.0,181.2,284.4,225.0,2957.4,156.7,236.1,1874.0,690.6
3,ANDAMAN & NICOBAR ISLANDS,1904,9.4,14.7,0.0,202.4,304.5,495.1,502.0,160.1,820.4,222.2,308.7,40.1,3079.6,24.1,506.9,1977.6,571.0
4,ANDAMAN & NICOBAR ISLANDS,1905,1.3,0.0,3.3,26.9,279.5,628.7,368.7,330.5,297.0,260.7,25.4,344.7,2566.7,1.3,309.7,1624.9,630.8

In [4]:
pricedata = pd.read_csv(r"../dataset/Price_Agriculture_commodities_Week.csv")
pricedata.head()

,State,District,Market,Commodity,Variety,Grade,Arrival_Date,Min Price,Max Price,Modal Price
0,Gujarat,Amreli,Damnagar,Bhindi(Ladies Finger),Bhindi,FAQ,27-07-2023,4100.0,4500.0,4350.0
1,Gujarat,Amreli,Damnagar,Brinjal,Other,FAQ,27-07-2023,2200.0,3000.0,2450.0
2,Gujarat,Amreli,Damnagar,Cabbage,Cabbage,FAQ,27-07-2023,2350.0,3000.0,2700.0
3,Gujarat,Amreli,Damnagar,Cauliflower,Cauliflower,FAQ,27-07-2023,7000.0,7500.0,7250.0
4,Gujarat,Amreli,Damnagar,Coriander(Leaves),Coriander,FAQ,27-07-2023,8400.0,9000.0,8850.0

In [5]:
print(cropdata.shape)
print(raindata.shape)
print(pricedata.shape)

(246091, 7)
(4116, 19)
(23093, 10)

In [6]:
cropdata.head()

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
0,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Arecanut,1254.0,2000.0
1,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Other Kharif pulses,2.0,1.0
2,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Rice,102.0,321.0
3,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Banana,176.0,641.0
4,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Cashewnut,720.0,165.0

In [7]:
raindata.head()

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
0,ANDAMAN & NICOBAR ISLANDS,1901,49.2,87.1,29.2,2.3,528.8,517.5,365.1,481.1,332.6,388.5,558.2,33.6,3373.2,136.3,560.3,1696.3,980.3
1,ANDAMAN & NICOBAR ISLANDS,1902,0.0,159.8,12.2,0.0,446.1,537.1,228.9,753.7,666.2,197.2,359.0,160.5,3520.7,159.8,458.3,2185.9,716.7
2,ANDAMAN & NICOBAR ISLANDS,1903,12.7,144.0,0.0,1.0,235.1,479.9,728.4,326.7,339.0,181.2,284.4,225.0,2957.4,156.7,236.1,1874.0,690.6
3,ANDAMAN & NICOBAR ISLANDS,1904,9.4,14.7,0.0,202.4,304.5,495.1,502.0,160.1,820.4,222.2,308.7,40.1,3079.6,24.1,506.9,1977.6,571.0
4,ANDAMAN & NICOBAR ISLANDS,1905,1.3,0.0,3.3,26.9,279.5,628.7,368.7,330.5,297.0,260.7,25.4,344.7,2566.7,1.3,309.7,1624.9,630.8

In [8]:
pricedata.head()

,State,District,Market,Commodity,Variety,Grade,Arrival_Date,Min Price,Max Price,Modal Price
0,Gujarat,Amreli,Damnagar,Bhindi(Ladies Finger),Bhindi,FAQ,27-07-2023,4100.0,4500.0,4350.0
1,Gujarat,Amreli,Damnagar,Brinjal,Other,FAQ,27-07-2023,2200.0,3000.0,2450.0
2,Gujarat,Amreli,Damnagar,Cabbage,Cabbage,FAQ,27-07-2023,2350.0,3000.0,2700.0
3,Gujarat,Amreli,Damnagar,Cauliflower,Cauliflower,FAQ,27-07-2023,7000.0,7500.0,7250.0
4,Gujarat,Amreli,Damnagar,Coriander(Leaves),Coriander,FAQ,27-07-2023,8400.0,9000.0,8850.0

In [9]:
cropdata.columns

Index(['State_Name', 'District_Name', 'Crop_Year', 'Season', 'Crop', 'Area',
       'Production'],
      dtype='object')

In [10]:
raindata.columns

Index(['SUBDIVISION', 'YEAR', 'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL',
       'AUG', 'SEP', 'OCT', 'NOV', 'DEC', 'ANNUAL', 'Jan-Feb', 'Mar-May',
       'Jun-Sep', 'Oct-Dec'],
      dtype='object')

In [11]:
pricedata.columns

Index(['State', 'District', 'Market', 'Commodity', 'Variety', 'Grade',
       'Arrival_Date', 'Min Price', 'Max Price', 'Modal Price'],
      dtype='object')

In [12]:
cropdata = cropdata.dropna(subset=['Area','Production'])

In [13]:
cropdata = cropdata[cropdata['Area']>0]

In [14]:
cropdata = cropdata[cropdata['Production']>0]

In [15]:
cropdata['Yield'] = cropdata['Production']/cropdata['Area']

In [16]:
cropdata = cropdata.rename(columns={
    'Crop_Year': 'Year'
})
cropdata['State_Name']    = cropdata['State_Name'].str.strip().str.title()
cropdata['District_Name'] = cropdata['District_Name'].str.strip().str.title()
cropdata['Crop']          = cropdata['Crop'].str.strip().str.title()
cropdata['Season']        = cropdata['Season'].str.strip().str.title()

In [17]:
print(cropdata['Season'].value_counts())
print("\n States: ", cropdata['State_Name'].nunique())
print("Crops: ",cropdata['Crop'].nunique())

Season
Kharif        93765
Rabi          65904
Whole Year    53385
Summer        14804
Winter         6050
Autumn         4930
Name: count, dtype: int64

 States:  33
Crops:  105

In [18]:
raindata = raindata[["SUBDIVISION","YEAR","ANNUAL"]]
raindata = raindata.rename(columns={
    'SUBDIVISION': 'State_Name',
    'YEAR': 'Year',
    'ANNUAL': 'Annual_Rainfall'
})
raindata['State_Name'] = raindata['State_Name'].str.strip().str.title()

In [19]:
raindata['State_Name'].unique()

array(['Andaman & Nicobar Islands', 'Arunachal Pradesh',
       'Assam & Meghalaya', 'Naga Mani Mizo Tripura',
       'Sub Himalayan West Bengal & Sikkim', 'Gangetic West Bengal',
       'Orissa', 'Jharkhand', 'Bihar', 'East Uttar Pradesh',
       'West Uttar Pradesh', 'Uttarakhand', 'Haryana Delhi & Chandigarh',
       'Punjab', 'Himachal Pradesh', 'Jammu & Kashmir', 'West Rajasthan',
       'East Rajasthan', 'West Madhya Pradesh', 'East Madhya Pradesh',
       'Gujarat Region', 'Saurashtra & Kutch', 'Konkan & Goa',
       'Madhya Maharashtra', 'Matathwada', 'Vidarbha', 'Chhattisgarh',
       'Coastal Andhra Pradesh', 'Telangana', 'Rayalseema', 'Tamil Nadu',
       'Coastal Karnataka', 'North Interior Karnataka',
       'South Interior Karnataka', 'Kerala', 'Lakshadweep'], dtype=object)

In [20]:
subdivision_to_state = {
    'Andaman & Nicobar Islands': 'Andaman And Nicobar Islands',
    'Arunachal Pradesh': 'Arunachal Pradesh',
    'Assam & Meghalaya': 'Assam',
    'Bihar': 'Bihar',
    'Chattisgarh': 'Chhattisgarh',
    'Coastal Andhra Pradesh': 'Andhra Pradesh',
    'Coastal Karnataka': 'Karnataka',
    'East Madhya Pradesh': 'Madhya Pradesh',
    'East Rajasthan': 'Rajasthan',
    'East Uttar Pradesh': 'Uttar Pradesh',
    'Gangetic West Bengal': 'West Bengal',
    'Gujarat Region': 'Gujarat',
    'Haryana Delhi & Chandigarh': 'Haryana',
    'Himachal Pradesh': 'Himachal Pradesh',
    'Jammu & Kashmir': 'Jammu And Kashmir',
    'Jharkhand': 'Jharkhand',
    'Kerala': 'Kerala',
    'Konkan & Goa': 'Goa',
    'Lakshadweep': 'Lakshadweep',
    'Madhya Maharashtra': 'Maharashtra',
    'Marathwada': 'Maharashtra',
    'Naga Mani Mizo Tripura': 'Nagaland',
    'North Interior Karnataka': 'Karnataka',
    'Orissa': 'Odisha',
    'Punjab': 'Punjab',
    'Rayalaseema': 'Andhra Pradesh',
    'Saurashtra & Kutch': 'Gujarat',
    'South Interior Karnataka': 'Karnataka',
    'Sub Himalayan West Bengal & Sikkim': 'West Bengal',
    'Tamil Nadu': 'Tamil Nadu',
    'Telangana': 'Telangana',
    'Uttarakhand': 'Uttarakhand',
    'Vidarbha': 'Maharashtra',
    'West Madhya Pradesh': 'Madhya Pradesh',
    'West Rajasthan': 'Rajasthan',
    'West Uttar Pradesh': 'Uttar Pradesh',
}
raindata['State_Name'] = raindata['State_Name'].map(subdivision_to_state)

In [21]:
raindata['State_Name'].unique()

array(['Andaman And Nicobar Islands', 'Arunachal Pradesh', 'Assam',
       'Nagaland', 'West Bengal', 'Odisha', 'Jharkhand', 'Bihar',
       'Uttar Pradesh', 'Uttarakhand', 'Haryana', 'Punjab',
       'Himachal Pradesh', 'Jammu And Kashmir', 'Rajasthan',
       'Madhya Pradesh', 'Gujarat', 'Goa', 'Maharashtra', nan,
       'Andhra Pradesh', 'Telangana', 'Tamil Nadu', 'Karnataka', 'Kerala',
       'Lakshadweep'], dtype=object)

In [22]:
raindata = raindata.dropna(subset=['State_Name'])

In [23]:
raindata = raindata.groupby(['State_Name', 'Year'])['Annual_Rainfall'].mean().reset_index()

In [24]:
pricedata.head()

,State,District,Market,Commodity,Variety,Grade,Arrival_Date,Min Price,Max Price,Modal Price
0,Gujarat,Amreli,Damnagar,Bhindi(Ladies Finger),Bhindi,FAQ,27-07-2023,4100.0,4500.0,4350.0
1,Gujarat,Amreli,Damnagar,Brinjal,Other,FAQ,27-07-2023,2200.0,3000.0,2450.0
2,Gujarat,Amreli,Damnagar,Cabbage,Cabbage,FAQ,27-07-2023,2350.0,3000.0,2700.0
3,Gujarat,Amreli,Damnagar,Cauliflower,Cauliflower,FAQ,27-07-2023,7000.0,7500.0,7250.0
4,Gujarat,Amreli,Damnagar,Coriander(Leaves),Coriander,FAQ,27-07-2023,8400.0,9000.0,8850.0

In [25]:
pricedata = pricedata.rename(columns={
    'State':'State_Name',
    'Commodity':'Crop',
    'Modal Price':'Price'
})

In [26]:
pricedata['State_Name'] = pricedata['State_Name'].str.strip().str.title()
pricedata['Crop']       = pricedata['Crop'].str.strip().str.title()
pricedata['Price']      = pd.to_numeric(pricedata['Price'], errors='coerce')

pricedata = pricedata.dropna(subset=['Price', 'Crop', 'State_Name'])
pricedata = pricedata[pricedata['Price'] > 0]

In [27]:
price_agg = pricedata.groupby(['State_Name', 'Crop'])['Price'].mean().reset_index()
price_agg.columns = ['State_Name', 'Crop', 'Avg_Price']

print(price_agg.shape)
price_agg.head()

(1308, 3)

            State_Name          Crop  Avg_Price
0  Andaman And Nicobar        Banana     9000.0
1  Andaman And Nicobar  Bitter Gourd    21000.0
2  Andaman And Nicobar  Bottle Gourd    12000.0
3  Andaman And Nicobar       Brinjal    15000.0
4  Andaman And Nicobar  Green Chilli    35000.0

In [28]:
merged = pd.merge(
    cropdata,
    raindata,
    on=['State_Name', 'Year'],
    how='left'
)
print("After rain merge:", merged.shape)
print("Rainfall nulls:", merged['Annual_Rainfall'].isnull().sum())

After rain merge: (238838, 9)
Rainfall nulls: 18790

In [29]:
merged = pd.merge(
    merged,
    price_agg,
    on=['State_Name', 'Crop'],
    how='left'
)
print("After price merge:", merged.shape)
print("Price nulls:", merged['Avg_Price'].isnull().sum())

After price merge: (238838, 10)
Price nulls: 182946

In [30]:
# merged = merged.dropna(subset=['Avg_Price'])

final_cols = ['State_Name', 'District_Name', 'Year', 'Season', 
              'Crop', 'Area', 'Production', 'Yield', 
              'Annual_Rainfall', 'Avg_Price']
merged = merged[final_cols]

print("Final shape:", merged.shape)
merged.head()

Final shape: (238838, 10)

,State_Name,District_Name,Year,Season,Crop,Area,Production,Yield,Annual_Rainfall,Avg_Price
0,Andaman And Nicobar Islands,Nicobars,2000,Kharif,Arecanut,1254.0,2000.0,1.594896,2763.2,NaN
1,Andaman And Nicobar Islands,Nicobars,2000,Kharif,Other Kharif Pulses,2.0,1.0,0.500000,2763.2,NaN
2,Andaman And Nicobar Islands,Nicobars,2000,Kharif,Rice,102.0,321.0,3.147059,2763.2,NaN
3,Andaman And Nicobar Islands,Nicobars,2000,Whole Year,Banana,176.0,641.0,3.642045,2763.2,NaN
4,Andaman And Nicobar Islands,Nicobars,2000,Whole Year,Cashewnut,720.0,165.0,0.229167,2763.2,NaN

In [31]:
matched = merged['Avg_Price'].notna().sum()
total = len(cropdata)
print(f"Price matched for {matched}/{total} rows ({100*matched/total:.1f}%)")

Price matched for 55892/238838 rows (23.4%)

In [32]:
unmatched_crops = merged[merged['Avg_Price'].isna()]['Crop'].unique()
matched_crops = price_agg['Crop'].unique()

print(f"Unmatched crop count: {len(unmatched_crops)}")
print("\nSample unmatched crops:")
print(sorted(unmatched_crops)[:30])

print("\nSample price dataset crops:")
print(sorted(matched_crops)[:30])

Unmatched crop count: 102

Sample unmatched crops:
['Arcanut (Processed)', 'Arecanut', 'Arhar/Tur', 'Atcanut (Raw)', 'Bajra', 'Banana', 'Barley', 'Bean', 'Beans & Mutter(Vegetable)', 'Bhindi', 'Bitter Gourd', 'Black Pepper', 'Blackgram', 'Bottle Gourd', 'Brinjal', 'Cabbage', 'Cardamom', 'Carrot', 'Cashewnut', 'Cashewnut Processed', 'Cashewnut Raw', 'Castor Seed', 'Cauliflower', 'Citrus Fruit', 'Coconut', 'Colocosia', 'Cond-Spcs Other', 'Coriander', 'Cotton(Lint)', 'Cowpea(Lobia)']

Sample price dataset crops:
['Ajwan', 'Alasande Gram', 'Almond(Badam)', 'Alsandikai', 'Amaranthus', 'Amla(Nelli Kai)', 'Amphophalus', 'Anthorium', 'Apple', 'Arecanut(Betelnut/Supari)', 'Arhar (Tur/Red Gram)(Whole)', 'Arhar Dal(Tur Dal)', 'Ashgourd', 'Bajra(Pearl Millet/Cumbu)', 'Banana', 'Banana - Green', 'Barley (Jau)', 'Beans', 'Beetroot', 'Bengal Gram Dal (Chana Dal)', 'Bengal Gram(Gram)(Whole)', 'Betal Leaves', 'Bhindi(Ladies Finger)', 'Bitter Gourd', 'Black Gram (Urd Beans)(Whole)', 'Black Gram Dal (Urd Dal)', 'Black Pepper', 'Bottle Gourd', 'Brinjal', 'Broomstick(Flower Broom)']

In [33]:
from fuzzywuzzy import process

# Build a mapping: crop_df crop name → best matching price_agg crop name
price_crops = price_agg['Crop'].unique().tolist()

def fuzzy_match_crop(crop_name, choices, threshold=80):
    match, score = process.extractOne(crop_name, choices)
    return match if score >= threshold else None

# Build mapping dict for unmatched crops only
crop_name_mapping = {}
for crop in unmatched_crops:
    best_match = fuzzy_match_crop(crop, price_crops)
    if best_match:
        crop_name_mapping[crop] = best_match

print(f"Fuzzy mapped {len(crop_name_mapping)} crops")
print("\nSample mappings:")
for k, v in list(crop_name_mapping.items())[:15]:
    print(f"  '{k}' → '{v}'")

d:\Python\Python312\Lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

Fuzzy mapped 71 crops

Sample mappings:
  'Arecanut' → 'Arecanut(Betelnut/Supari)'
  'Rice' → 'Rice'
  'Banana' → 'Banana'
  'Cashewnut' → 'Cashewnuts'
  'Coconut' → 'Coconut'
  'Dry Ginger' → 'Ginger(Dry)'
  'Sugarcane' → 'Sugar'
  'Sweet Potato' → 'Sweet Potato'
  'Tapioca' → 'Tapioca'
  'Black Pepper' → 'Black Pepper'
  'Dry Chillies' → 'Dry Chillies'
  'Turmeric' → 'Turmeric'
  'Maize' → 'Maize'
  'Moong(Green Gram)' → 'Arhar (Tur/Red Gram)(Whole)'
  'Arhar/Tur' → 'Arhar (Tur/Red Gram)(Whole)'

In [34]:
manual_fixes = {
    'Moong(Green Gram)'      : 'Green Gram',        # fix wrong match
    'Sugarcane'              : 'Sugarcane',          # 'Sugar' is wrong
    'Other Cereals & Millets': None,                 # no good match, drop
    'Other Kharif Pulses'    : None,
    'Other Rabi Pulses'      : None,
    'Other Summer Pulses'    : None,
    'Other Vegetables'       : None,
    'Other Misc. Crops'      : None,
}

for crop, fix in manual_fixes.items():
    if fix is None:
        crop_name_mapping.pop(crop, None)
    else:
        crop_name_mapping[crop] = fix

In [35]:
print("ALL 71 FUZZY MAPPINGS:")
print("-" * 50)
for k, v in sorted(crop_name_mapping.items()):
    print(f"  '{k}' → '{v}'")

ALL 71 FUZZY MAPPINGS:
--------------------------------------------------
  'Arecanut' → 'Arecanut(Betelnut/Supari)'
  'Arhar/Tur' → 'Arhar (Tur/Red Gram)(Whole)'
  'Atcanut (Raw)' → 'Groundnut Pods (Raw)'
  'Bajra' → 'Bajra(Pearl Millet/Cumbu)'
  'Banana' → 'Banana'
  'Barley' → 'Barley (Jau)'
  'Bean' → 'Black Gram (Urd Beans)(Whole)'
  'Beans & Mutter(Vegetable)' → 'Beans'
  'Bhindi' → 'Bhindi(Ladies Finger)'
  'Bitter Gourd' → 'Bitter Gourd'
  'Black Pepper' → 'Black Pepper'
  'Blackgram' → 'Black Gram (Urd Beans)(Whole)'
  'Bottle Gourd' → 'Bottle Gourd'
  'Brinjal' → 'Brinjal'
  'Cabbage' → 'Cabbage'
  'Cardamom' → 'Cardamoms'
  'Carrot' → 'Carrot'
  'Cashewnut' → 'Cashewnuts'
  'Cashewnut Processed' → 'Cashewnuts'
  'Castor Seed' → 'Castor Seed'
  'Cauliflower' → 'Cauliflower'
  'Coconut' → 'Coconut'
  'Coriander' → 'Coriander(Leaves)'
  'Cotton(Lint)' → 'Cotton'
  'Cowpea(Lobia)' → 'Cow'
  'Drum Stick' → 'Drumstick'
  'Dry Chillies' → 'Dry Chillies'
  'Dry Ginger' → 'Ginger(Dry)'
  'Garlic' → 'Garlic'
  'Ginger' → 'Ginger(Green)'
  'Gram' → 'Arhar (Tur/Red Gram)(Whole)'
  'Grapes' → 'Grapes'
  'Groundnut' → 'Groundnut'
  'Guar Seed' → 'Guar'
  'Horse-Gram' → 'Kulthi(Horse Gram)'
  'Jack Fruit' → 'Jack Fruit'
  'Jowar' → 'Jowar(Sorghum)'
  'Jute' → 'Jute'
  'Jute & Mesta' → 'Jute'
  'Lentil' → 'Lentil (Masur)(Whole)'
  'Linseed' → 'Linseed'
  'Maize' → 'Maize'
  'Mango' → 'Mango'
  'Moong(Green Gram)' → 'Green Gram'
  'Niger Seed' → 'Niger Seed (Ramtil)'
  'Onion' → 'Onion'
  'Orange' → 'Orange'
  'Paddy' → 'Paddy(Dhan)(Common)'
  'Papaya' → 'Papaya'
  'Peas & Beans (Pulses)' → 'Beans'
  'Pineapple' → 'Pineapple'
  'Pome Granet' → 'Pomegranate'
  'Potato' → 'Potato'
  'Ragi' → 'Ragi (Finger Millet)'
  'Rapeseed &Mustard' → 'Mustard'
  'Rice' → 'Rice'
  'Ricebean (Nagadal)' → 'Rice'
  'Rubber' → 'Rubber'
  'Safflower' → 'Safflower'
  'Sapota' → 'Chikoos(Sapota)'
  'Sesamum' → 'Sesamum(Sesame,Gingelly,Til)'
  'Soyabean' → 'Soyabean'
  'Sugarcane' → 'Sugarcane'
  'Sunflower' → 'Sunflower'
  'Sweet Potato' → 'Sweet Potato'
  'Tapioca' → 'Tapioca'
  'Tobacco' → 'Tobacco'
  'Tomato' → 'Tomato'
  'Turmeric' → 'Turmeric'
  'Varagu' → 'Kodo Millet(Varagu)'
  'Wheat' → 'Wheat'

In [36]:
cropdata['Crop'] = cropdata['Crop'].replace(crop_name_mapping)
cropdata['Crop'] = cropdata['Crop'].fillna(cropdata['Crop'])

In [37]:
# Apply fuzzy mapping to crop_df
cropdata['Crop'] = cropdata['Crop'].replace(crop_name_mapping)
# For already-matched crops, keep original name
cropdata['Crop'] = cropdata['Crop'].fillna(cropdata['Crop'])

# Re-merge from scratch using matched crop name
merged2 = pd.merge(cropdata, raindata, on=['State_Name', 'Year'], how='left')

merged2 = pd.merge(
    merged2,
    price_agg,
    on=['State_Name', 'Crop'],
    how='left'
)

merged2 = merged2.dropna(subset=['Avg_Price'])

# Check improvement
matched2 = merged2['Avg_Price'].notna().sum()
total = len(cropdata)
print(f"✅ After fuzzy fix: {matched2}/{total} rows ({100*matched2/total:.1f}%)")

✅ After fuzzy fix: 94062/238838 rows (39.4%)

In [38]:
merged2.head()

,State_Name,District_Name,Year,Season,Crop,Area,Production,Yield,Annual_Rainfall,Avg_Price
201,Andhra Pradesh,Anantapur,1997,Kharif,Arhar (Tur/Red Gram)(Whole),21400.0,2600.0,0.121495,972.1,8600.000
203,Andhra Pradesh,Anantapur,1997,Kharif,Castor Seed,1000.0,100.0,0.100000,972.1,6126.500
204,Andhra Pradesh,Anantapur,1997,Kharif,Cotton,7300.0,9400.0,1.287671,972.1,7050.000
205,Andhra Pradesh,Anantapur,1997,Kharif,Dry Chillies,3700.0,7100.0,1.918919,972.1,18712.625
206,Andhra Pradesh,Anantapur,1997,Kharif,Groundnut,650800.0,228400.0,0.350953,972.1,6964.600

In [39]:
final_cols = ['State_Name', 'District_Name', 'Year', 'Season', 
              'Crop', 'Area', 'Production', 'Yield', 
              'Annual_Rainfall', 'Avg_Price']

merged2 = merged2[final_cols]

merged2.to_csv('../dataset/merged_crop_data.csv', index=False)
print("✅ Saved!")
print("Final shape:", merged2.shape)
merged2.head()

✅ Saved!
Final shape: (94062, 10)

,State_Name,District_Name,Year,Season,Crop,Area,Production,Yield,Annual_Rainfall,Avg_Price
201,Andhra Pradesh,Anantapur,1997,Kharif,Arhar (Tur/Red Gram)(Whole),21400.0,2600.0,0.121495,972.1,8600.000
203,Andhra Pradesh,Anantapur,1997,Kharif,Castor Seed,1000.0,100.0,0.100000,972.1,6126.500
204,Andhra Pradesh,Anantapur,1997,Kharif,Cotton,7300.0,9400.0,1.287671,972.1,7050.000
205,Andhra Pradesh,Anantapur,1997,Kharif,Dry Chillies,3700.0,7100.0,1.918919,972.1,18712.625
206,Andhra Pradesh,Anantapur,1997,Kharif,Groundnut,650800.0,228400.0,0.350953,972.1,6964.600